### ISSUE TITLE
Project failing to return results

### ISSUE THREAD

**Issue by rippll-miles** [ferreirix/restratp#1]
Hi,

The project is failing to return any results - I have tried to run it locally and I am receiving errors.
for example
var directions = await ratpService.getDirectionsAsync(new getDirectionsRequest(line)); is shown as an error
Also http://restratpws.azurewebsites.net/api/lines/metro is not working.
I'd really like to use the project!

**Comment by ferreirix** [comment]
Hey,

It's an issue with the azure outbound ip address. Please try again.

If you want to run it locally you have to register your origin ip address
within RATP. You have to fill a form, send an email and wait. Yes, not very
efficient..

You can also check out my react project that's using this API:
http://ratp.azurewebsites.net

Cheers

**Comment by rippll-miles** [comment]
Thanks!
Works now I have my IP address registered.

Are all fields from the SDK exposed in this project ?

Thanks,

**Comment by ferreirix** [comment]
No, it's a lighter API than the official one.
